HealthPro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('facility.urls')),
    path('patient/', include('records.urls')),
    path('sponsor/', include('sponsor.urls')),
    path('visitation/', include('visitation.urls')),
]

records/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add/', views.PatientCreateView.as_view(), name='patient_add'),
    path('all/', views.PatientListView.as_view(), name='patient_list'),
    path('<patient_id>/', views.PatientDetailView.as_view(), name='patient_detail'),
    path('<patient_id>/edit', views.PatientUpdateView.as_view(), name='patient_edit'),
    path('<patient_id>/next_of_kin/edit', views.PatientNextOfKinEditView.as_view(), name='patient_nextofkin_edit'),
    
]

Records/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.

class Title(models.Model):
    TitleName = models.CharField(_("Title Name"), max_length=255)
    Description = models.TextField(blank=True, null=True)
    Status = models.BooleanField(_("Relation Type Status"), default=True)

    class Meta:
        verbose_name = "Title"
        verbose_name_plural = "Titles"
    
    def __str__(self) -> str:
        return f'{self.TitleName}'

class RelationType(models.Model):
    RelationTypeName = models.CharField(_("Relation Type"), max_length=255)
    Description = models.TextField(blank=True, null=True)
    Status = models.BooleanField(_("Relation Type Status"), default=True)

    class Meta:
        verbose_name = "Relation Type"
        verbose_name_plural = "Relation Types"
    
    def __str__(self) -> str:
        return f'{self.RelationTypeName}'

class PatientType(models.Model):
    PatientTypeName = models.CharField(_("Patient Type Name"), max_length=255)
    Description = models.TextField(blank=True, null=True)
    Status = models.BooleanField(_("Relation Type Status"), default=True)

    class Meta:
        verbose_name = "Patient Type"
        verbose_name_plural = "Patient Types"
    
    def __str__(self) -> str:
        return f'{self.PatientTypeName}'

class Gender(models.Model):
    GenderName = models.CharField(_("Gender Name"), max_length=255)
    Description = models.TextField(blank=True, null=True)
    Status = models.BooleanField(_("Relation Type Status"), default=True)

    class Meta:
        verbose_name = "Gender"
        verbose_name_plural = "Genders"
    
    def __str__(self) -> str:
        return f'{self.GenderName}'

class MaritalStatus(models.Model):
    MaritalStatusName = models.CharField(_("Marital Status Name"), max_length=255)
    Description = models.TextField(blank=True, null=True)
    Status = models.BooleanField(_("Relation Type Status"), default=True)

    class Meta:
        verbose_name = "Marital Status"
        verbose_name_plural = "Marital Statuses"
    
    def __str__(self) -> str:
        return f'{self.MaritalStatusName}'

class PatientInsScheme(models.Model):
    PatientInsSchemeID = models.CharField(_("Insurance Scheme ID"), max_length=255)
    PatientInsSchemeName = models.CharField(_("Insurance Scheme Name"), max_length=255)
    Address = models.TextField(_("Address"), blank=True, null=True)
    City = models.CharField(_("City"), blank=True, null=True, max_length=255)
    Location = models.CharField(_("Location"), blank=True, null=True, max_length=255)
    OfficePhone = models.CharField(_("Office Phone"), blank=True, null=True, max_length=255)
    OfficeFax = models.CharField(_("Office Fax"), blank=True, null=True, max_length=255)
    Description = models.TextField(blank=True, null=True)
    Status = models.BooleanField(_("Relation Type Status"), default=True)

    class Meta:
        verbose_name = "Insurance Scheme"
        verbose_name_plural = "Insurance Schemes"
    
    def __str__(self) -> str:
        return f'{self.PatientInsSchemeID}'

class Country(models.Model):
    CountryName = models.CharField(_("Country"), max_length=255)
    Description = models.TextField(blank=True, null=True)
    Status = models.BooleanField(_("Relation Type Status"), default=True)

    class Meta:
        verbose_name = "Country"
        verbose_name_plural = "Countries"
    
    def __str__(self) -> str:
        return f'{self.CountryName}'

class Religion(models.Model):
    ReligionName = models.CharField(_("Name of Religion"), max_length=255)
    Description = models.TextField(blank=True, null=True)
    Status = models.BooleanField(_("Relation Type Status"), default=True)

    class Meta:
        verbose_name = "Religion"
        verbose_name_plural = "Religions"
    
    def __str__(self) -> str:
        return f'{self.ReligionName}'

class DependentType(models.Model):
    DependentName = models.CharField(_("Name of Religion"), max_length=255)
    Description = models.TextField(blank=True, null=True)
    Status = models.BooleanField(_("Relation Type Status"), default=True)

    class Meta:
        verbose_name = "Dependent Type"
        verbose_name_plural = "Dependent Types"
    
    def __str__(self) -> str:
        return f'{self.DependentName}'

class Patient(models.Model):
    EmailAddress = models.CharField(_("Email Address"), max_length=255)
    TitleID = models.ForeignKey(Title, verbose_name = _("Title"), on_delete=models.SET_DEFAULT, default='1')
    FirstName = models.CharField(_("First Name"), max_length=255)
    SurName = models.CharField(_("Surname"), max_length=255)
    OtherName = models.CharField(_("Other Name"), max_length=255)
    BirthDate = models.DateField(_("Date of Birth"))
    PatientTypeID = models.ForeignKey(PatientType, verbose_name =  _("Patient Type"), on_delete=models.SET_DEFAULT, default='NONE')
    GenderID = models.ForeignKey(Gender,  verbose_name = _("Gender"), on_delete=models.SET_NULL, null=True)
    Occupation = models.CharField(_("Occupation"), max_length=255)
    BusinessPhone = models.CharField(_("Business Phone"), max_length=255)
    ResidencePhone = models.CharField(_("Business Phone"), max_length=255)
    ResidenceAddress = models.TextField(_("Residence Address"))
    BusinessAddress = models.TextField(_("Business Address"), blank=True, null=True)
    CountryID = models.ForeignKey(Country, verbose_name =  _("Country"), on_delete=models.SET_DEFAULT, default='NONE')
    ReligionID = models.ForeignKey(Religion, verbose_name =  _("Religion"), on_delete=models.SET_DEFAULT, default='NONE')
    MaritalStatusID = models.ForeignKey(MaritalStatus, verbose_name =  _("Marital Status"), on_delete=models.SET_DEFAULT, default='NONE')
    PatientInsSchemeID = models.ForeignKey(PatientInsScheme, verbose_name = _("Patient Insurance Scheme"), on_delete=models.SET_NULL, null=True)
    PatientInsNo = models.CharField(_("Patient Insurance Number"), max_length=255)
    PatientDependentTypeID = models.ForeignKey(DependentType, verbose_name =  _("Dependent"), on_delete=models.SET_DEFAULT, default='SELF')
    CreatedAt = models.DateTimeField(auto_now_add=True)
    Status = models.BooleanField(_("Relation Type Status"), default=True)

    class Meta:
        verbose_name = "Patient"
        verbose_name_plural = "Patients"
    
    def __str__(self) -> str:
        return

class PatientRank(models.Model):
    PatientRankName = models.CharField(_("Patient Rank Name"), max_length=255)
    Description = models.TextField(blank=True, null=True)
    Status = models.BooleanField(_("Relation Type Status"), default=True)

    class Meta:
        verbose_name = "Patient Rank"
        verbose_name_plural = "Patient Ranks"
    
    def __str__(self) -> str:
        return f'{self.PatientRankName}'

class PatientRankLevel(models.Model):
    PatientRankLevelName = models.CharField(_("Patient Rank Level Name"), max_length=255)
    Description = models.TextField(blank=True, null=True)
    Status = models.BooleanField(_("Relation Type Status"), default=True)

    class Meta:
        verbose_name = "Patient Rank Level"
        verbose_name_plural = "Patient Rank Levels"
    
    def __str__(self) -> str:
        return f'{self.PatientRankLevelName}'

class PatientUnit(models.Model):
    PatientUnitName = models.CharField(_("Patient Unit"), max_length=255)
    Description = models.TextField(blank=True, null=True)
    Status = models.BooleanField(_("Relation Type Status"), default=True)

    class Meta:
        verbose_name = "Patient Unit"
        verbose_name_plural = "Patient Units"
    
    def __str__(self) -> str:
        return f'{self.PatientUnitName}'

class IdentificationType(models.Model):
    IdentificationTypeName = models.CharField(_("Type of Identification"), max_length=255)
    Description = models.TextField(blank=True, null=True)
    Status = models.BooleanField(_("Relation Type Status"), default=True)

    class Meta:
        verbose_name = "Identification Type"
        verbose_name_plural = "Identification Types"
    
    def __str__(self) -> str:
        return f'{self.IdentificationTypeName}'

class NextOfKin(models.Model):
    NextOfKinID = models.CharField(_("Next of Kin ID"), max_length=255, unique=True)
    PatientID = models.ForeignKey(Patient, verbose_name = _("Patient"),  on_delete=models.CASCADE, db_index=True)
    NextOfKinName = models.CharField(_("Name of Next of Kin"), max_length=255)
    PatientTypeID = models.ForeignKey(PatientType, verbose_name = _("Patient Category"), on_delete=models.SET_DEFAULT, default=1)
    RelationTypeID = models.ForeignKey(RelationType, verbose_name = _("Relation with Patient"), on_delete=models.SET_NULL, null=True)
    ContactAddress = models.TextField()
    DateOfBirth = models.DateField(_("Date of Birth"))
    Email = models.CharField(_("Email Address"), max_length=255, blank=True, null=True)
    Profession = models.CharField(_("Profession"), max_length=255)
    CreatedAt = models.DateTimeField(_("Date Created"), auto_now_add=True)
    EntryDate = models.DateTimeField(_("Entry Date"), auto_now_add=True)
    KeyPrefix = models.CharField(_("Key Prefix"), blank=True, null=True, max_length=255)
    PatientRankID = models.ForeignKey(PatientRank, verbose_name =  _("Patient Rank"), on_delete=models.SET_NULL, null=True)
    PatientRankLevelID = models.ForeignKey(PatientRankLevel, verbose_name =  _("Patient Rank Level"), on_delete=models.SET_NULL, null=True)
    PatientUnitID = models.ForeignKey(PatientUnit, verbose_name =  _("Patient Unit"), on_delete=models.SET_NULL, null=True)
    ServiceNo = models.CharField(_("Service No."), max_length=255)
    IdentificationTypeID = models.ForeignKey(IdentificationType, verbose_name =  _("ID Type"), on_delete=models.SET_NULL, null=True)
    IdentificationNumber = models.CharField(_("ID Number"), max_length=255)    
    Status = models.BooleanField(_("Next of Kin Status"), default=True)

    class Meta:

visitation/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from facility.models import Branch, Department
from records.models import Patient
from sponsor.models import BillingAccount
from consultation.models import ConsultationType
from cashier.models import Receipt
import helpers

# Create your models here.

def generateVisitTypeID():
    qs = VisitType.objects.all()
    return helpers.generateID('V', qs=qs, length=4)

def generateVisitStatusID():
    qs = VisitStatus.objects.all()
    return helpers.generateID('V', qs=qs, length=4)

class VisitType(models.Model):
    '''
    Model definition for types of Visitations: First time, Subsequent, Review, Emergency
    '''
    VisitTypeID = models.CharField(_("Visit Type ID"), max_length=250, default=generateVisitTypeID)
    VisitTypeName = models.CharField(_("Visit Type"), max_length=50)
    VisitTypeCost = models.DecimalField(_("Visit Type Cost"), max_digits=5, decimal_places=2, default=0.00)
    Description = models.TextField(_("Desccription"), blank=True, null=True, editable=False)
    Status = models.BooleanField(_("Status of Visit Type"), default=True, editable=False)
    CreatedAt = models.DateField(_("Created At"), auto_now_add=True)

    class Meta:
        verbose_name = _("Visit Type")
        verbose_name_plural = _("Visit Types")

    def __str__(self):
        return self.VisitTypeName

    def get_absolute_url(self):
        return reverse("visit_type_detail", kwargs={"visit_type_id": self.VisitTypeID})

class VisitStatus(models.Model):
    '''Model definition for status of visitation: unattended, diagnosed, etc'''
    VisitStatusID = models.CharField(_("Visit Status ID"), max_length=250, default=generateVisitStatusID)
    VisitStatusName = models.CharField(_("Visit Status Name"), max_length=250)
    Description = models.TextField(_("Desccription"), blank=True, null=True, editable=False)
    Status = models.BooleanField(_("Status of Visit Type"), default=True, editable=False)
    CreatedAt = models.DateField(_("Created At"), auto_now_add=True)
    

    class Meta:
        verbose_name = _("Visit Status")
        verbose_name_plural = _("Visit Statuses")

    def __str__(self):
        return self.VisitStatusName

    def get_absolute_url(self):
        return reverse("visit_status_detail", kwargs={"visit_status_id": self.VisitStatusID})


def generateVisitationID():
    qs = Visitation.objects.all()
    return helpers.generateVisitationID(qs=qs)

class Visitation(models.Model):
    '''Model definition for visitations / hospital attendance'''
    VisitationID = models.CharField(_("Visitation ID"), max_length=250, default=generateVisitationID, unique=True)
    VisitationName = models.CharField(_("Visitation Name"), max_length=250, blank=True, editable=False, null=True)
    VisitStatusID = models.ForeignKey(VisitStatus, verbose_name=_("Status"), on_delete=models.SET_NULL, null=True)
    PatientID = models.ForeignKey(Patient, verbose_name=_("Patient"), on_delete=models.CASCADE)
    VisitTypeID = models.ForeignKey(VisitType, verbose_name=_("Visit Type"), on_delete=models.SET_NULL, null=True)
    DepartmentID = models.ForeignKey(Department, verbose_name=_("Department"), on_delete=models.SET_NULL, null=True)
    ConsultationTypeID = models.ForeignKey(ConsultationType, verbose_name=_("Consultation Type"), on_delete=models.SET_NULL, null=True)
    BillingAccountID = models.ForeignKey(BillingAccount, verbose_name=_("Billing Account"), on_delete=models.CASCADE)
    VisitationFee = models.CharField(_("Consultation Fee"), max_length=250)
    ManualReceiptNumber = models.CharField(_("Manual Receipt Number"), max_length=250, blank=True, null=True)
    ReceiptNumber = models.ForeignKey(Receipt, verbose_name=_("Receipt"), on_delete=models.CASCADE, blank=True, null=True)
    VisitDate = models.DateField(_("Visit Date"), auto_now_add=True)
    Description = models.TextField(_("Desccription"), blank=True, null=True, editable=False)
    Status = models.BooleanField(_("Status of Visit Type"), default=True, editable=False)
    CreatedAt = models.DateField(_("Created At"), auto_now_add=True)
    

    class Meta:
        verbose_name = _("Visitation")
        verbose_name_plural = _("Visitations")

    def __str__(self):
        return f'{self.PatientID} -- [{self.VisitationID}]'

    def get_absolute_url(self):
        return reverse("visitation_detail", kwargs={"visitation_id": self.VisitationID})

records/forms.py
from django import forms
from .models import Patient, NextOfKin

class PatientForm(forms.ModelForm):
    
    class Meta:
        model = Patient
        exclude = ('CreatedAt', 'Status', 'PatientRankLevel', 'PatientRank', 'PatientCategory')
        widgets = {
            'FirstName': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'SurName': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'SurName'}),
            'OtherName': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Other Name'}),
            'PatientID': forms.TextInput(attrs={'class': 'form-control w-25'}),
            'TitleID': forms.Select(attrs={'class': 'form-control custom-select'}),
            'GenderID': forms.Select(attrs={'class': 'form-control custom-select', 'placeholder': 'Select Gender'}),
            'EmailAddress': forms.EmailInput(attrs={'class': 'form-control'}),
            'BirthDate': forms.DateInput(attrs={'class': 'form-control w-50', 'placeholder': 'yyyy-mm-dd'}),
            'MaritalStatusID': forms.Select(attrs={'class': 'form-control'}),
            'CountryID': forms.Select(attrs={'class': 'form-control custom-select', 'placeholder': 'Select Country'}),
            'ReligionID': forms.Select(attrs={'class': 'form-control custom-select', 'placeholder': 'Select Religion'}),
            'Occupation': forms.TextInput(attrs={'class': 'form-control'}),
            'BusinessPhone': forms.TextInput(attrs={'class': 'form-control'}),
            'BusinessAddress': forms.TextInput(attrs={'class': 'form-control'}),
            'ResidencePhone': forms.TextInput(attrs={'class': 'form-control'}),
            'ResidenceAddress': forms.TextInput(attrs={'class': 'form-control'}),
        
        }

PatientNextOfKinFormSet = forms.inlineformset_factory(
    Patient, 
    NextOfKin, 
    fields=('NextOfKinID', 'NextOfKinName', 'RelationTypeID', 'ContactAddress',), 
    extra=1,
    widgets={
        'NextOfKinID': forms.TextInput(attrs={'class': 'form-control'}),
        'NextOfKinName': forms.TextInput(attrs={'class': 'form-control'}),
        'RelationTypeID': forms.Select(attrs={'class': 'form-control'}),
        'ContactAddress': forms.TextInput(attrs={'class': 'form-control'}),
    }
)

templates/records/patient_add.html
{% extends 'extras/base.html' %}
{% block title %}Add Patient{% endblock title %}

{% block content %}
  <div>
    <h2>Add Patient</h2>
  </div>
    {{ form.hidden_fields.errors }}
    <form method='post'>
        {% csrf_token %}
        <div class="form-group">  
        {{form.PatientID.errors}}
        {{ form.PatientID.label }} 
        {{ form.PatientID }}
        </div>
        <div class="row">
          <div class="form-group col-md-4">
            {{form.TitleID.errors}}
              {{form.TitleID.label}}
              {{form.TitleID}}
          </div>
          <div class="form-group col-md-4">
            {{form.GenderID.errors}}
              {{form.GenderID.label}}
              {{form.GenderID}}
          </div>
          <div class="form-group col-md-4">
            {{form.MaritalStatusID.errors}}
              {{form.MaritalStatusID.label}}
              {{form.MaritalStatusID}}
          </div>
        </div>
        <div class="row">
          <div class="form-group col-md-4">
            {{form.SurName.errors}}
              {{form.SurName.label}}
              {{form.SurName}}
          </div>
          <div class="form-group col-md-4">
            {{form.OtherName.errors}}
              {{form.OtherName.label}}
              {{form.OtherName}}
          </div>
          <div class="form-group col-md-4">
            {{form.FirstName.errors}}
            {{form.FirstName.label}}
            {{form.FirstName}}
          </div>
        </div>
        <div class="row">
          <div class="form-group col-md-4">
              {{form.BirthDate.errors}}
              {{form.BirthDate.label}}
              {{form.BirthDate}}
          </div>
          <div class="form-group col-md-4">
            {{form.Occupation.errors}}
            {{form.Occupation.label}}
            {{form.Occupation}}
        </div>
          <div class="form-group col-md-4">
              {{form.EmailAddress.errors}}
              {{form.EmailAddress.label}}
              {{form.EmailAddress}}
          </div>
        <div class="row">
            <div class="form-group col-md-6">
                {{form.BusinessPhone.errors}}
                {{form.BusinessPhone.label}}
                {{form.BusinessPhone}}
            </div>
            <div class="form-group col-md-6">
                {{form.ResidencePhone.errors}}
                {{form.ResidencePhone.label}}
                {{form.ResidencePhone}}
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                {{form.BusinessAddress.errors}}
                {{form.BusinessAddress.label}}
                {{form.BusinessAddress}}
            </div>
            <div class="form-group col-md-6">
                {{form.ResidenceAddress.errors}}
                {{form.ResidenceAddress.label}}
                {{form.ResidenceAddress}}
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                {{form.CountryID.errors}}
                {{form.CountryID.label}}
                {{form.CountryID}}
            </div>
            <div class="form-group col-md-6">
                {{form.ReligionID.errors}}
                {{form.ReligionID.label}}
                {{form.ReligionID}}
            </div>
        </div>
        <input type="submit" class="btn btn-primary my-3 pd-3" value="Submit">
    </form>
    
{% endblock content %}

templates/records/patient_detail.html
{% extends 'extras/base.html' %}
{% load static %}
{% block title %} {{patient}} - [{{patient.PatientID}}]{% endblock title %}

{% block content %}
<div id="patient-info-title">
    <h5 class="d-inline">Patient Information&nbsp;&nbsp;&nbsp;</h5> <h5 class="d-inline">| <a class="edit-info-link" href="{% url 'patient_edit' patient.PatientID %}"><i class="fa fa-pencil fa-fw"></i> Edit Patient Record</a></h5>
</div>
<div class="info" class="mb-2">
<table class="table table-borderless">
    <tbody>
        <tr>
            <td style="text-align: right;">First Name:</td>
            <td style="text-align: left;"><strong>{{patient.FirstName}}</strong></td>
            
            {% if patient.OtherName %}
                <td style="text-align: right;">Other Name:</td>
                <td style="text-align: left;"><strong>{{patient.OtherName}}</strong></td>
            {% endif %}
            <td style="text-align: right;">SurName:</td>
            <td style="text-align: left;"><strong>{{patient.SurName}}</strong></td>
            {% if not patient.OtherName %}
                <td style="text-align: right;">Patient ID:</td>
                <td style="text-align: left;"><strong>{{patient.PatientID}}</strong></td>
            {% endif %}
        </tr>
        <tr>
            {% if patient.OtherName %}
                <td style="text-align: right;">Patient ID:</td>
                <td style="text-align: left;"><strong>{{patient.PatientID}}</strong></td>
            {% endif %}
        </tr>
        <tr>
            <td style="text-align: right;">Gender:</td>
            <td style="text-align: left;"><strong>{{patient.GenderID}}</strong></td>
            <td style="text-align: right;">Age:</td>
            <td style="text-align: left;"><strong>{{patient.getAge}}</strong></td>
            <td style="text-align: right;">Religion:</td>
            <td style="text-align: left;"><strong>{{patient.ReligionID}}</strong></td>
        </tr>
        <tr>
            <td style="text-align: right;">Mobile:</td>
            <td style="text-align: left;"><strong>{{patient.ResidencePhone}}</strong></td>
            <td style="text-align: right;">Address:</td>
            <td style="text-align: left;"><strong>{{patient.ResidenceAddress}}</strong></td>
            <td style="text-align: right;">Occupation:</td>
            <td style="text-align: left;"><strong>{{patient.Occupation}}</strong></td>
        </tr>
    </tbody>
</table>
</div>
<div id="nextofkin-info-title" class="mt-2">
    <h5 class="d-inline">Next of Kin Information&nbsp;&nbsp;&nbsp;</h5> <h5 class="d-inline">| <a class="edit-info-link" href="{% url 'patient_nextofkin_edit' patient.PatientID %}">Add Next Of Kin</a></h5>
</div>

{% if patient.nextofkin_set.all %}
    <div class="info">
        <table class="table table-borderless">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name of Next of Kin</th>
                    <th>Relation to Patient</th>
                    <th>Address</th>
                </tr>
            </thead>
            <tbody>
                {% for nextofkin in patient.nextofkin_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{nextofkin.NextOfKinName}}</td>
                        <td>{{nextofkin.RelationTypeID}}</td>
                        <td>{{nextofkin.ContactAddress}}</td>
                        <td><i class="bi bi-pencil">edit</i></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}
    
<div id="insurance-info-title" class="mt-2">
    <h5 class="d-inline">Billing Account Information&nbsp;&nbsp;&nbsp;</h5> 
    <h5 class="d-inline">| <a class="edit-info-link" href="{% url 'sponsor_add' patient.PatientID %}">
        <i class="fa-solid fa-wallet fa-fw"></i>
        Add Billing Account
        </a>
    </h5>
</div>

{% if patient.billingaccount_set.all %}
    <div class="info">
        <table class="table table-borderless">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Sponsor</th>
                    <th>Scheme</th>
                    <th>Type</th>
                    <th>Scheme No.</th>
                    <th>Status</th>
                    <th>Expiry Date</th>
                    <th>Entry Date</th>
                </tr>
            </thead>
            <tbody>
                {% for billing_account in patient.billingaccount_set.all %}
                    <tr class='billing-info'>
                        <td>{{forloop.counter}}</td>
                        <td>{{billing_account.InsuranceSchemeID.SponsorID}}</td>
                        <td>{{billing_account.InsuranceSchemeID}}</td>
                        <td>{{billing_account.RelationTypeID}}</td>
                        <td>{{billing_account.BillingAccountID}}</td>
                        <td
                            
                            {% if billing_account.SponsorStatusID.id == 1 %}
                                class="text-success"
                            {% else %}
                                class="text-danger"
                            {% endif %}
                                
                        >
                            {{billing_account.SponsorStatusID}}
                        </td>
                        <td>{{billing_account.ExpiryDate|date:'l, F j, Y'}}</td>
                        <td>{{billing_account.CreatedAt|date:'l, F j, Y'}}</td>
                    </tr>
                    <tr>
                        <td></td>
                        {% comment %} <td></td> {% endcomment %}
                        <td colspan="7">
                            <table class="table table-borderless">
                                <th>Visit Information &nbsp;&nbsp;&nbsp; | Add New Visit</th>
                                <tbody>
                                    
                                    {% if billing_account.visitation_set.all %}
                                    <tr>
                                        <td><b>Visit ID</b></td><td><b>Visit Type</b></td><td><b>Consultation Type</b></td><td><b>Visit Status</b></td><td><b>Visit Date</b></td>
                                    </tr>    
                                    
                                    {% for visit in billing_account.visitation_set.all %}
                                        <tr>
                                        <td>{{visit.VisitationID}}</td><td>{{visit.VisitTypeID}}</td><td>{{visit.ConsultationTypeID}}</td><td>{{visit.VisitStatusID}}</td><td>{{visit.VisitDate|date:'l, F j, Y'}}</td>
                                        </tr>
                                    {% endfor %}
                                                        
                                    {% endif %}
                    
                                </tbody>
                            </table>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}
    
{% endblock content %}

templates/records/patient_list.html
{% extends 'extras/base.html' %}
{% block title %}
Patient List
{% endblock title %}

{% block content %}
    <h1>Patient List</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Patient ID</th>
                <th>Name</th>
                <th>Gender</th>
                <th>BirthDate</th>
                <th>Occupation</th>
                <th>Business Phone</th>
            </tr>
        </thead>
        <tbody>
            
            {% if patients %}
                {% for patient in patients %}
                    <tr>
                        <td scope="row"><a href="{% url 'patient_detail' patient.PatientID %}">{{patient.PatientID}}</a></td>
                        <td>{{patient}}</td>
                        <td>{{patient.GenderID}}</td>
                        <td>{{patient.BirthDate}}</td>
                        <td>{{patient.Occupation}}</td>
                        <td>{{patient.BusinessPhone}}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <p>No Patient Registered
            {% endif %}
        </tbody>
    </table>
    
{% endblock content %}